"""followers association table

Revision ID: 12de9a7b0040
Revises: 20adae857ed5
Create Date: 2019-10-01 16:18:40.223295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12de9a7b0040'
down_revision = '20adae857ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
