"""new fields in user model

Revision ID: 20adae857ed5
Revises: 7bb73bd569b8
Create Date: 2019-10-01 13:16:14.635695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20adae857ed5'
down_revision = '7bb73bd569b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
